import type { PersistedState } from "@/types";

export const demoSeed: PersistedState = {
  tasks: [
    {
      id: "t-react",
      title: "Learn React fundamentals",
      description:
        "Get comfortable with components, state and effects before touching a framework on top.",
      categoryId: "c-prog",
      deadline: "2026-08-14",
      status: "active",
      createdAt: "2026-07-10T09:00:00.000Z",
      updatedAt: "2026-07-10T09:00:00.000Z",
      source: "ai_recommendation",
      aiReason:
        "You finished the JavaScript basics course, so React is the natural next step.",
      subtasks: [
        { id: "s1", title: "Understand JSX and rendering", done: true },
        { id: "s2", title: "Practise props and state", done: true },
        { id: "s3", title: "Learn the effect lifecycle", done: false },
        { id: "s4", title: "Build a small component library", done: false },
        { id: "s5", title: "Review and fill the gaps", done: false },
      ],
      order: 0,
      edited: false,
      resources: [
        {
          id: "r1",
          kind: "book",
          title: "Learning React",
          author: "Alex Banks and Eve Porcello",
          year: 2020,
          note: "A practical, project-driven route through modern React.",
          read: true,
        },
        {
          id: "r2",
          kind: "book",
          title: "The Pragmatic Programmer",
          author: "Andrew Hunt and David Thomas",
          year: 1999,
          note: "Habits that keep a growing codebase maintainable.",
          read: false,
        },
        {
          id: "r3",
          kind: "article",
          title: "Thinking in React",
          url: "https://react.dev/learn/thinking-in-react",
          note: "The official walkthrough of decomposing a UI into components.",
          read: true,
        },
        {
          id: "r4",
          kind: "course",
          title: "CS50: Introduction to Computer Science",
          author: "Harvard University",
          url: "https://cs50.harvard.edu/x/",
          note: "Fills in the computing fundamentals behind the framework.",
          read: false,
        },
      ],
    },
    {
      id: "t-sql",
      title: "Revise SQL joins and indexing",
      description:
        "Joins still slow me down under time pressure, and I cannot reason about indexes yet.",
      categoryId: "c-prog",
      deadline: "2026-07-25",
      status: "active",
      createdAt: "2026-07-05T09:00:00.000Z",
      updatedAt: "2026-07-18T09:00:00.000Z",
      source: "manual",
      subtasks: [
        { id: "s6", title: "Redo the join exercises", done: true },
        { id: "s7", title: "Read up on index types", done: false },
        { id: "s8", title: "Explain three slow queries", done: false },
      ],
      order: 1,
      edited: true,
      resources: [
        {
          id: "r5",
          kind: "book",
          title: "Designing Data-Intensive Applications",
          author: "Martin Kleppmann",
          year: 2017,
          note: "Explains why indexes behave the way they do, not just how to add one.",
          read: false,
        },
        {
          id: "r6",
          kind: "article",
          title: "SQL Joins Explained",
          author: "freeCodeCamp",
          url: "https://www.freecodecamp.org/news/sql-joins-tutorial/",
          note: "A short refresher with diagrams for each join type.",
          read: false,
        },
      ],
    },
    {
      id: "t-ielts",
      title: "Prepare for the IELTS exam",
      description: "Target band 7.5, writing is the weakest section.",
      categoryId: "c-lang",
      deadline: "2026-09-15",
      status: "active",
      createdAt: "2026-07-12T09:00:00.000Z",
      updatedAt: "2026-07-12T09:00:00.000Z",
      source: "ai_prompt",
      aiReason:
        "This plan turns your stated goal into a sequence you can start this week.",
      subtasks: [
        { id: "s9", title: "Take a diagnostic mock test", done: false },
        { id: "s10", title: "Drill writing task 2 twice a week", done: false },
        { id: "s11", title: "Build an academic vocabulary deck", done: false },
        { id: "s12", title: "Practise timed reading", done: false },
        { id: "s13", title: "Do a full mock under exam conditions", done: false },
      ],
      order: 2,
      edited: false,
      resources: [
        {
          id: "r7",
          kind: "book",
          title: "Fluent Forever",
          author: "Gabriel Wyner",
          year: 2014,
          note: "A concrete method for vocabulary that actually stays learned.",
          read: false,
        },
        {
          id: "r8",
          kind: "book",
          title: "How Languages Are Learned",
          author: "Patsy Lightbown and Nina Spada",
          year: 1993,
          note: "Explains why some study routines work and others waste time.",
          read: false,
        },
      ],
    },
    {
      id: "t-linalg",
      title: "Work through linear algebra basics",
      description:
        "Needed before starting anything serious in machine learning.",
      categoryId: "c-math",
      deadline: "2026-08-05",
      status: "active",
      createdAt: "2026-07-14T09:00:00.000Z",
      updatedAt: "2026-07-14T09:00:00.000Z",
      source: "manual",
      subtasks: [
        { id: "s14", title: "Vectors and spans", done: false },
        { id: "s15", title: "Matrix multiplication as composition", done: false },
        { id: "s16", title: "Determinants", done: false },
        { id: "s17", title: "Eigenvalues and eigenvectors", done: false },
      ],
      order: 3,
      edited: false,
      resources: [
        {
          id: "r9",
          kind: "book",
          title: "Linear Algebra Done Right",
          author: "Sheldon Axler",
          year: 1997,
          note: "Builds the subject from vector spaces rather than from matrix arithmetic.",
          read: false,
        },
        {
          id: "r10",
          kind: "course",
          title: "Khan Academy: Linear Algebra",
          author: "Khan Academy",
          url: "https://www.khanacademy.org/math/linear-algebra",
          note: "Good for filling one specific gap without a whole curriculum.",
          read: false,
        },
      ],
    },
    {
      id: "t-habits",
      title: "Build a repeatable study routine",
      description:
        "Sessions are irregular, so most of what I read does not stick.",
      status: "active",
      createdAt: "2026-07-20T09:00:00.000Z",
      updatedAt: "2026-07-20T09:00:00.000Z",
      source: "ai_recommendation",
      aiReason:
        "Your completed tasks cluster in bursts, which is the pattern spaced review fixes.",
      subtasks: [
        { id: "s18", title: "Pick two fixed study slots", done: false },
        { id: "s19", title: "Set up spaced review", done: false },
        { id: "s20", title: "Track sessions for two weeks", done: false },
      ],
      order: 4,
      edited: false,
      resources: [
        {
          id: "r11",
          kind: "book",
          title: "Make It Stick",
          author: "Peter Brown, Henry Roediger and Mark McDaniel",
          year: 2014,
          note: "What the research says about how learning actually sticks.",
          read: true,
        },
        {
          id: "r12",
          kind: "course",
          title: "Learning How to Learn",
          author: "McMaster University",
          url: "https://www.coursera.org/learn/learning-how-to-learn",
          note: "A short course on study strategy that pays for itself early.",
          read: false,
        },
      ],
    },
    {
      id: "t-js",
      title: "Finish the JavaScript basics course",
      description: "Closures and async were the hard parts.",
      categoryId: "c-prog",
      deadline: "2026-07-01",
      status: "done",
      createdAt: "2026-06-08T09:00:00.000Z",
      updatedAt: "2026-06-30T09:00:00.000Z",
      completedAt: "2026-06-30T09:00:00.000Z",
      source: "manual",
      subtasks: [
        { id: "s21", title: "Syntax and types", done: true },
        { id: "s22", title: "Functions and closures", done: true },
        { id: "s23", title: "Promises and async/await", done: true },
      ],
      order: 5,
      edited: false,
      resources: [
        {
          id: "r13",
          kind: "article",
          title: "Using the Fetch API",
          author: "MDN Web Docs",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch",
          note: "The reference I kept coming back to for async requests.",
          read: true,
        },
      ],
    },
    {
      id: "t-proofs",
      title: "Learn to read mathematical proofs",
      description: "Textbook proofs were unreadable before this.",
      categoryId: "c-math",
      status: "done",
      createdAt: "2026-06-15T09:00:00.000Z",
      updatedAt: "2026-07-08T09:00:00.000Z",
      completedAt: "2026-07-08T09:00:00.000Z",
      source: "ai_recommendation",
      aiReason: "Proof literacy unblocks the maths reading you had queued.",
      subtasks: [
        { id: "s24", title: "Logic and quantifiers", done: true },
        { id: "s25", title: "Direct and contrapositive proofs", done: true },
        { id: "s26", title: "Induction", done: true },
      ],
      order: 6,
      edited: false,
      resources: [
        {
          id: "r14",
          kind: "book",
          title: "How to Prove It",
          author: "Daniel J. Velleman",
          year: 1994,
          note: "Bridges the gap between computation and mathematical reasoning.",
          read: true,
        },
      ],
    },
  ],
  categories: [
    { id: "c-prog", name: "Programming", createdAt: "2026-06-01T09:00:00.000Z" },
    { id: "c-lang", name: "Languages", createdAt: "2026-06-03T09:00:00.000Z" },
    { id: "c-math", name: "Mathematics", createdAt: "2026-06-05T09:00:00.000Z" },
  ],
  activeTab: "active",
};
